package derecho

import (
	"context"

	"github.com/atmonostorm/derecho/journal"
)

// StubExecutionState is a minimal ExecutionState for unit tests.
// Use for scheduler tests and as a base for test harnesses.
type StubExecutionState struct {
	events    []journal.Event
	newEvents []journal.Event
	lastID    int
}

func NewStubExecutionState() *StubExecutionState {
	return &StubExecutionState{}
}

func (s *StubExecutionState) NewRecorder(afterEventID int) Recorder {
	if afterEventID > s.lastID {
		s.lastID = afterEventID
	}
	return &stubRecorder{state: s}
}

func (s *StubExecutionState) GetByScheduledID(scheduledEventID int) []journal.Event {
	var result []journal.Event
	for _, ev := range s.events {
		if ev.Base().ScheduledByID == scheduledEventID {
			result = append(result, ev)
		}
	}
	for _, ev := range s.newEvents {
		if ev.Base().ScheduledByID == scheduledEventID {
			result = append(result, ev)
		}
	}
	return result
}

func (s *StubExecutionState) GetSignals(signalName string) []journal.SignalReceived {
	var result []journal.SignalReceived
	for _, ev := range s.events {
		if sig, ok := ev.(journal.SignalReceived); ok && sig.SignalName == signalName {
			result = append(result, sig)
		}
	}
	return result
}

// AddExternalEvent appends an event as if it arrived from outside the workflow.
func (s *StubExecutionState) AddExternalEvent(ev journal.Event) int {
	s.lastID++
	s.events = append(s.events, ev.WithID(s.lastID))
	return s.lastID
}

// Events returns all recorded events.
func (s *StubExecutionState) Events() []journal.Event {
	return s.events
}

// NewEvents returns events generated by the scheduler (not external events).
func (s *StubExecutionState) NewEvents() []journal.Event {
	return s.newEvents
}

type stubRecorder struct {
	state   *StubExecutionState
	pending []journal.Event
}

func (r *stubRecorder) Record(eventType string, generate func() journal.Event) (journal.Event, error) {
	event := generate()
	r.state.lastID++
	event = event.WithID(r.state.lastID)
	r.pending = append(r.pending, event)
	r.state.newEvents = append(r.state.newEvents, event)
	return event, nil
}

func (r *stubRecorder) Commit(ctx context.Context, scheduledAtTask int) error {
	r.state.events = append(r.state.events, r.pending...)
	r.pending = nil
	return nil
}

func (r *stubRecorder) PendingCount() int {
	return len(r.pending)
}
